# BUILD SECTIONS
FROM node:20 as build

WORKDIR /build-app
COPY  . /build-app/

ENV NODE_VERSION=18.16.0

# NPM
RUN npm install -g pnpm
RUN pnpm install

# BUILD APP
RUN pnpm build

# BUILD SECTIONS
FROM node:20 as production

WORKDIR /prod-app

COPY --from=build /build-app/package.json ./package.json
COPY --from=build /build-app/dist ./dist
COPY --from=build /build-app/.env ./.env

# INSTALL PROD DEPENDENCIES
RUN ls
RUN npm install -g pnpm
RUN pnpm install --prod --ignore-scripts
RUN npm rebuild bcrypt
RUN rm -rf ./.npmrc

#  START APP
CMD pnpm start:prod
